/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 shoppingCart.gltf --transform 
Files: shoppingCart.gltf [18.36KB] > shoppingCart-transformed.glb [11.26KB] (39%)
Author: AdrianXY (https://sketchfab.com/adrianxy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shopping-cart-b96f896453b240ae804d0399f1faf027
Title: Shopping Cart
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/shoppingCart-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_4.geometry}
				material={materials.material}
				scale={6.489}
			/>
			<mesh
				geometry={nodes.Object_5.geometry}
				material={materials.Griff}
				scale={6.489}
			/>
			<mesh
				geometry={nodes.Object_6.geometry}
				material={materials.Chrome}
				scale={6.489}
			/>
		</group>
	);
}

useGLTF.preload("/shoppingCart-transformed.glb");
